### ISSUE TITLE
Vale de entrada

### ISSUE THREAD

**Issue by benjamcadev** [benjamcadev/CDS#28]
La idea es que el vale de entrada se pueda reciclar o copiar componentes de el vale de salida, seria ideal re utilizarlos pero debido a la complejidad y como fue construido el vale de salida no podemos re utilizar el mismo componente, pero crearemos una copia de ellos.

Se ha creado la branch **feature/vale-entrada** para que trabajes toda la nueva caracteristica, hay 3 componentes nuevos que se crearon a partir del vale de salida:

- En Pages <ValeEntrada />
- En Componentes <FormularioValeEntrada />
- En Componentes <TablaEntrada />

El componente <FormularioValeEntrada /> **es el mas importante** ya que contiene el State de los datos que se enviaran al backend
const [datos, setDatos] = useState({})

Aca en este state debes ir almacenando todos los datos (datos de inputs, de select, firmas, imagenes, detalle de tabla, etc.)

Los campos dentro del formulario van a ser dinamicos, me explico iran cambiando (Apareciendo y ocultandose) dependiendo del tipo de ticket de entrada, los tipos de entrada pueden ser:

![image](https://github.com/user-attachments/assets/ec4cccbd-5dd9-46b1-bf6a-ab0db49b1fce)

Estos ya estan definidos en la Base De datos

Entonces por ejemplo si tienes un tipo de ticket "Devolucion" tienen que haber inputs como, quien esta devolviendo el material, porque lo esta devolviendo, observaciones, etc.

Si tienes un tipo devolucion "Guia despacho" debe haber un input que te pida el numero de la Guia despacho, y por ejemplo en la tabla en cada Row seria ideal colocar una columna que te pida el numero de reserva o de OC

Los campos bases que debiesen ir en el formulario serian:

- Fecha
- Tipo de ingreso (Devolucion, guia despacho, etc)
- Responsable bodega quien esta haciendo el ingreso de material
- Observaciones
- Firma responsable bodega.

Campos que iran variando:

En caso de devolucion:
- Motivo de devolucion
- Quien esta devolviendo material
- 1 sola foto de los materiales que se devolvieron (Se va hacer un espacio en el meson de material en transito exclusivo para la devolucion ahi se sacara la foto)
- Firma de la persona que esta devolviendo

En caso de guia despacho
- Numero de Guia despacho
- Tipo de recepcion (Puede ser retiro en bodega 6 o despacho en TICA)
- 1 Foto de la guia despacho para respaldo
- Que la tabla habilite poder ingresar un numero que puede ser una reserva o una Orden de Compra, esto para cada material.

Es posible que tengamos que ir modificando la base de datos para que se acople a lo que se esta desarrollando.

Eso por el momento el lunes veremos el ticket fisico y veremos si podemos complementar mas.

**Comment by FrancoDev7** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?05834C1D3E080B4E5C34E491FF09174AE1DD
